[package]
name = "day10"
version = "0.1.0"
authors = ["Tim Ousborne <dev@sourbone.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
